### ISSUE TITLE
Invalid clinet URI

### ISSUE THREAD

**Issue by xstrex** [Nezreka/Spotify-Plex-Playlist-Sync#2]
Running on a mac, after rebuilding the venv and installing all the requirements. Python 3.12.6

Opens new tab, as expected with url: `https://accounts.spotify.com/authorize?client_id=<redacted>&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8888%2Fcallback&scope=playlist-read-private+playlist-read-collaborative`

Error: `INVALID_CLIENT: Invalid redirect URI`

**Comment by Nezreka** [comment]
Is the proper callback set in your Spotify app in the dashboard? If it's
something different you can adjust the spotify_service.py to point where
you have it set

**Comment by xstrex** [comment]
That did it, thanks! Works well.
